<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('productos')->insert([
            // FOTOGRAFIA (categoria_id = 1)
            [
                'producto_id' => 1,
                'nombre'      => 'Canon EOS R6 Mark II (cuerpo)',
                'cantidad'    => 5,
                'precio'      => 2599.00,
                'codigo'      => 'CAM-CAN-R6M2-BODY',
                'foto'        => 'https://i1.adis.ws/i/canon/5666C028_EOS-R6-Mark-II_01?w=1200&bg=rgb(245,246,246)&fmt=webp&qlt=100&sm=aspect&aspect=1:1',
                'descripcion' => 'Cámara full-frame con excelente rendimiento en ráfaga y AF para fotografía deportiva y de eventos. Estabilización en el cuerpo (IBIS) y buen rendimiento en ISO alto.',
                'categoria_id' => 1,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 2,
                'nombre'      => 'Fujifilm X-T5 (cuerpo)',
                'cantidad'    => 8,
                'precio'      => 1899.00,
                'codigo'      => 'CAM-FUJ-XT5-BODY',
                'foto'        => 'https://eshop.fujifilm-x.com/media/catalog/product/cache/495b3925f2d882830dd92457c3f7d74d/x/-/x-t5_front_sensor_background_image_2_1.jpg',
                'descripcion' => 'Cámara APS-C de 40MP con excelente color y sistema de simulación de película. Ideal para retrato y fotografía de estudio.',
                'categoria_id' => 1,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 3,
                'nombre'      => 'Sony Alpha A7 IV (cuerpo)',
                'cantidad'    => 4,
                'precio'      => 2799.00,
                'codigo'      => 'CAM-SON-A7IV-BODY',
                'foto'        => 'https://sony.scene7.com/is/image/sonyglobalsolutions/01_mobile-5?$productIntroPlatemobile$&fmt=png-alpha',
                'descripcion' => 'Híbrida full-frame 33MP con un balance entre foto y vídeo; AF avanzado y soporte amplio de lentes FE.',
                'categoria_id' => 1,
                'created_at'  => $now,
                'updated_at' => $now,
            ],

            // VIDEO (categoria_id = 2)
            [
                'producto_id' => 4,
                'nombre'      => 'Blackmagic Pocket Cinema Camera 6K G2',
                'cantidad'    => 3,
                'precio'      => 1995.00,
                'codigo'      => 'VID-BMD-P6KG2',
                'foto'        => 'https://images.blackmagicdesign.com/images/media/press-images/blackmagic-pocket-cinema-camera-6k-g2/blackmagic-pocket-cinema-camera-6k-g2-hero.jpg?_v=1652403088',
                'descripcion' => 'Cámara de cine 6K con sensor Super 35, grabación en Blackmagic RAW y ProRes; pensada para producción de vídeo profesional y documentales.',
                'categoria_id' => 2,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 5,
                'nombre'      => 'Panasonic Lumix S5 II (cuerpo)',
                'cantidad'    => 4,
                'precio'      => 1999.00,
                'codigo'      => 'VID-PAN-S5II',
                'foto'        => 'https://shop.panasonic.com/cdn/shop/products/hmnjoeh0ptr0f1wqivhm.jpg?v=1692726228&width=1000',
                'descripcion' => 'Cámara mirrorless full-frame orientada a vídeo: estabilización, perfiles log y buena gestión térmica para tomas largas.',
                'categoria_id' => 2,
                'created_at'  => $now,
                'updated_at' => $now,
            ],

            // OBJETIVOS (categoria_id = 3)
            [
                'producto_id' => 6,
                'nombre'      => 'Canon RF 50mm f/1.8 STM',
                'cantidad'    => 15,
                'precio'      => 229.00,
                'codigo'      => 'LEN-CAN-RF50F18',
                'foto'        => 'https://cdn.media.amplience.net/i/canon/rf50mm-f1.8-stm-slant-with-cap-product-gallery-05_ad7da2365ae24cd481be5b9569ddeb99?$prod-gallery-1by1$',
                'descripcion' => 'Pequeño y ligero "nifty fifty" para montura RF. Buen rendimiento en retrato y baja luz, relación calidad-precio excelente.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 7,
                'nombre'      => 'Sony FE 24-70mm f/2.8 GM II',
                'cantidad'    => 3,
                'precio'      => 2399.00,
                'codigo'      => 'LEN-SON-2470GM2',
                'foto'        => 'https://sony.scene7.com/is/image/sonyglobalsolutions/SEL2470GM2_Product_Intro_1_M?$productIntroPlatemobile$&fmt=png-alpha',
                'descripcion' => 'Zoom estándar profesional con excelente nitidez y sellado climático; ideal para bodas, eventos y producción comercial.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 8,
                'nombre'      => 'Sigma 18-35mm f/1.8 DC HSM Art (Canon EF)',
                'cantidad'    => 6,
                'precio'      => 799.00,
                'codigo'      => 'LEN-SIG-1835ART-EF',
                'foto'        => 'https://www.sigma-photo.es/250-thickbox_default/sigma-18-35mm-f18-dc-hsm-art.jpg',
                'descripcion' => 'Objetivo luminoso para APS-C; muy valorado en vídeo por su apertura constante y calidad óptica.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],

            // ACCESORIOS (categoria_id = 4)
            [
                'producto_id' => 9,
                'nombre'      => 'Trípode Manfrotto Befree Advanced',
                'cantidad'    => 10,
                'precio'      => 199.00,
                'codigo'      => 'ACC-MAN-BEFREE-ADV',
                'foto'        => 'https://cdn.manfrotto.com/media/catalog/product/p/r/professional-photo-tripod-befree-advanced-nerissimo-mkbfrta4bm-bh.jpg',
                'descripcion' => 'Trípode compacto y resistente, pensado para viajar. Compatible con cámaras mirrorless y DSLR ligeras.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 10,
                'nombre'      => 'Tarjeta SDXC 128GB UHS-II V90',
                'cantidad'    => 25,
                'precio'      => 129.90,
                'codigo'      => 'ACC-SDXC-128-V90',
                'foto'        => 'https://shop.sandisk.com/content/dam/store/en-us/assets/products/memory-cards/extreme-pro-uhs-ii-v90-sd/gallery/extreme-pro-uhs-ii-v90-sd-128gb-front.png.wdthumb.1280.1280.webp',
                'descripcion' => 'Tarjeta de alta velocidad para grabaciones 4K/6K y ráfagas prolongadas; indicada para cámaras profesionales.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 11,
                'nombre'      => 'Rode VideoMic NTG',
                'cantidad'    => 7,
                'precio'      => 249.00,
                'codigo'      => 'ACC-ROD-VIDNTG',
                'foto'        => 'https://edge.rode.com/images/page/127/modules/4128/R%C3%98DE_VM-NTG_3-QUARTER_FRONT_1080x1080.png',
                'descripcion' => 'Micrófono shotgun híbrido con salida TRS y USB; ideal para creadores de contenido y vídeos en exteriores.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 12,
                'nombre'      => 'DJI RS 4 (gimbal)',
                'cantidad'    => 2,
                'precio'      => 549.00,
                'codigo'      => 'ACC-DJI-RS4',
                'foto'        => 'https://se-cdn.djiits.com/tpc/uploads/carousel/image/4b242cc807cf292db63827f10cb2687e@ultra.jpg',
                'descripcion' => 'Estabilizador 3 ejes para cámaras mirrorless y DSLR ligeras; buen soporte de carga y modos de seguimiento.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 13,
                'nombre'      => 'Monopié Cayer',
                'cantidad'    => 15,
                'precio'      => 120.00,
                'codigo'      => 'ACC-CAY-MP22',
                'foto'        => 'https://i1.adis.ws/i/canon/5666C028_EOS-R6-Mark-II_01?w=1200&bg=rgb(245,246,246)&fmt=webp&qlt=100&sm=aspect&aspect=1:1',
                'descripcion' => Monopié profesional de aleación de aluminio con cierre rápido y base plegable. Ideal para fotografía deportiva y de naturaleza. Soporta hasta 10 kg y cuenta con empuñadura antideslizante.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 14,
                'nombre'      => 'Sony FE 70-200mm f/2.8 GM OSS II',
                'cantidad'    => 8,
                'precio'      => 2599.00,
                'codigo'      => 'LEN-SON-GMII',
                'foto'        => 'https://i1.adis.ws/i/canon/5666C028_EOS-R6-Mark-II_01?w=1200&bg=rgb(245,246,246)&fmt=webp&qlt=100&sm=aspect&aspect=1:1',
                'descripcion' => 'Teleobjetivo zoom de la serie G Master con apertura constante f/2.8. Enfoque automático rápido y silencioso, elementos XA para máxima nitidez, y recubrimiento Nano AR II que reduce reflejos y destellos. Ideal para deportes, retratos y naturaleza.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 15,
                'nombre'      => 'Sony FX3 Cinema Line',
                'cantidad'    => 3,
                'precio'      => 4599.00,
                'codigo'      => 'CAM-SON-FX3-BODY',
                'foto'        => 'https://i1.adis.ws/i/canon/5666C028_EOS-R6-Mark-II_01?w=1200&bg=rgb(245,246,246)&fmt=webp&qlt=100&sm=aspect&aspect=1:1',
                'descripcion' => 'Cámara de cine compacta con sensor full-frame Exmor R de 10.2 MP, grabación 4K hasta 120p, ISO extendido hasta 409.600, montura E y diseño con ventilador activo. Pensada para producciones cinematográficas y creadores de contenido profesionales.',
                'categoria_id' => 2,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
