<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductosSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('productos')->insert([
            [
                'producto_id' => 1,
                'nombre'      => 'Canon EOS R6 Mark II (cuerpo)',
                'cantidad'    => 5,
                'precio'      => 2599.00,
                'codigo'      => 'CAM-CAN-R6M2-BODY',
                'foto'        => 'https://i.ibb.co/7JgXFbsP/Canon-EOS-R6-Mark-II-cuerpo.png',
                'descripcion' => 'Cámara full-frame con excelente rendimiento en ráfaga y AF para fotografía deportiva y de eventos. Estabilización en el cuerpo (IBIS) y buen rendimiento en ISO alto.',
                'categoria_id' => 1,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 2,
                'nombre'      => 'Fujifilm X-T5 (cuerpo)',
                'cantidad'    => 8,
                'precio'      => 1899.00,
                'codigo'      => 'CAM-FUJ-XT5-BODY',
                'foto'        => 'https://i.ibb.co/JwNwH63C/Fujifilm-X-T5.png',
                'descripcion' => 'Cámara APS-C de 40MP con excelente color y sistema de simulación de película. Ideal para retrato y fotografía de estudio.',
                'categoria_id' => 1,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 3,
                'nombre'      => 'Sony Alpha A7 IV (cuerpo)',
                'cantidad'    => 4,
                'precio'      => 2799.00,
                'codigo'      => 'CAM-SON-A7IV-BODY',
                'foto'        => 'https://i.ibb.co/84MLSxw4/Sony-Alpha-A7-IV.png',
                'descripcion' => 'Híbrida full-frame 33MP con un balance entre foto y vídeo; AF avanzado y soporte amplio de lentes FE.',
                'categoria_id' => 1,
                'created_at'  => $now,
                'updated_at' => $now,
            ],

            [
                'producto_id' => 4,
                'nombre'      => 'Blackmagic Pocket Cinema Camera 6K G2',
                'cantidad'    => 3,
                'precio'      => 1995.00,
                'codigo'      => 'VID-BMD-P6KG2',
                'foto'        => 'https://i.ibb.co/V07MCG4d/Blackmagic-Pocket-Cinema-Camera-6-K-G2.png',
                'descripcion' => 'Cámara de cine 6K con sensor Super 35, grabación en Blackmagic RAW y ProRes; pensada para producción de vídeo profesional y documentales.',
                'categoria_id' => 2,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 5,
                'nombre'      => 'Panasonic Lumix S5 II (cuerpo)',
                'cantidad'    => 4,
                'precio'      => 1999.00,
                'codigo'      => 'VID-PAN-S5II',
                'foto'        => 'https://i.ibb.co/jkqgQgPH/Lumix-S5-II.png',
                'descripcion' => 'Cámara mirrorless full-frame orientada a vídeo: estabilización, perfiles log y buena gestión térmica para tomas largas.',
                'categoria_id' => 2,
                'created_at'  => $now,
                'updated_at' => $now,
            ],

            [
                'producto_id' => 6,
                'nombre'      => 'Canon RF 50mm f/1.8 STM',
                'cantidad'    => 15,
                'precio'      => 229.00,
                'codigo'      => 'LEN-CAN-RF50F18',
                'foto'        => 'https://i.ibb.co/LhrscwkK/Canon-RF-50mm-f-1-8-STM.png',
                'descripcion' => 'Pequeño y ligero "nifty fifty" para montura RF. Buen rendimiento en retrato y baja luz, relación calidad-precio excelente.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 7,
                'nombre'      => 'Sony FE 24-70mm f/2.8 GM II',
                'cantidad'    => 3,
                'precio'      => 2399.00,
                'codigo'      => 'LEN-SON-2470GM2',
                'foto'        => 'https://i.ibb.co/7dzkwR90/Sony-FE-24-70mm-f2-8-GMII.png',
                'descripcion' => 'Zoom estándar profesional con excelente nitidez y sellado climático; ideal para bodas, eventos y producción comercial.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 8,
                'nombre'      => 'Sigma 18-35mm f/1.8 DC HSM Art (Canon EF)',
                'cantidad'    => 6,
                'precio'      => 799.00,
                'codigo'      => 'LEN-SIG-1835ART-EF',
                'foto'        => 'https://i.ibb.co/8Dw1LTkW/sigma-18-35mm-f18-dc-hsm-art.png',
                'descripcion' => 'Objetivo luminoso para APS-C; muy valorado en vídeo por su apertura constante y calidad óptica.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],

            [
                'producto_id' => 9,
                'nombre'      => 'Trípode Manfrotto Befree Advanced',
                'cantidad'    => 10,
                'precio'      => 199.00,
                'codigo'      => 'ACC-MAN-BEFREE-ADV',
                'foto'        => 'https://i.ibb.co/HDtCqKkd/Tr-pode-Manfrotto-Befree-Advanced.png',
                'descripcion' => 'Trípode compacto y resistente, pensado para viajar. Compatible con cámaras mirrorless y DSLR ligeras.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 10,
                'nombre'      => 'Tarjeta SDXC 128GB UHS-II V90',
                'cantidad'    => 25,
                'precio'      => 129.90,
                'codigo'      => 'ACC-SDXC-128-V90',
                'foto'        => 'https://i.ibb.co/939hnxNb/tarjeta-SDXC-128-GB-UHS-II-V90.png',
                'descripcion' => 'Tarjeta de alta velocidad para grabaciones 4K/6K y ráfagas prolongadas; indicada para cámaras profesionales.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 11,
                'nombre'      => 'Rode VideoMic NTG',
                'cantidad'    => 7,
                'precio'      => 249.00,
                'codigo'      => 'ACC-ROD-VIDNTG',
                'foto'        => 'https://i.ibb.co/DfcGWgYb/Rode-Video-Mic-NTG.png',
                'descripcion' => 'Micrófono shotgun híbrido con salida TRS y USB; ideal para creadores de contenido y vídeos en exteriores.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 12,
                'nombre'      => 'DJI RS 4 (gimbal)',
                'cantidad'    => 2,
                'precio'      => 549.00,
                'codigo'      => 'ACC-DJI-RS4',
                'foto'        => 'https://i.ibb.co/p6BGNnPb/DJI-RS-4-gimbal.png',
                'descripcion' => 'Estabilizador 3 ejes para cámaras mirrorless y DSLR ligeras; buen soporte de carga y modos de seguimiento.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 13,
                'nombre'      => 'Monopié Cayer',
                'cantidad'    => 15,
                'precio'      => 120.00,
                'codigo'      => 'ACC-CAY-MP22',
                'foto'        => 'https://i.ibb.co/ynVYxcCZ/Monopi-Cayer.png',
                'descripcion' => 'Monopié profesional de aleación de aluminio con cierre rápido y base plegable. Ideal para fotografía deportiva y de naturaleza. Soporta hasta 10 kg y cuenta con empuñadura antideslizante.',
                'categoria_id' => 4,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 14,
                'nombre'      => 'Sony FE 70-200mm f/2.8 GM OSS II',
                'cantidad'    => 8,
                'precio'      => 2599.00,
                'codigo'      => 'LEN-SON-GMII',
                'foto'        => 'https://i.ibb.co/dJ4K5QXs/Sony-70-200-2-8-GMII.png',
                'descripcion' => 'Teleobjetivo zoom de la serie G Master con apertura constante f/2.8. Enfoque automático rápido y silencioso, elementos XA para máxima nitidez, y recubrimiento Nano AR II que reduce reflejos y destellos. Ideal para deportes, retratos y naturaleza.',
                'categoria_id' => 3,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
            [
                'producto_id' => 15,
                'nombre'      => 'Sony FX3 Cinema Line',
                'cantidad'    => 3,
                'precio'      => 4599.00,
                'codigo'      => 'CAM-SON-FX3-BODY',
                'foto'        => 'https://i.ibb.co/TD516Q2Q/Sony-FX3.png',
                'descripcion' => 'Cámara de cine compacta con sensor full-frame Exmor R de 10.2 MP, grabación 4K hasta 120p, ISO extendido hasta 409.600, montura E y diseño con ventilador activo. Pensada para producciones cinematográficas y creadores de contenido profesionales.',
                'categoria_id' => 2,
                'created_at'  => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
